### ISSUE TITLE
Suggest to add DI decorators in `deps` array for angular-dependency-injection-infographic

### ISSUE THREAD

**Issue by phhien203** [ChristianKohler/Homepage#32]
Hi Christian,

Regarding to the angular-dependency-injection-infographic, section 4. Other ways to register, I would suggest the following content

We can use DI decorators in `deps` array, like this
```
providers: [
    {
      provide: SOME_TOKEN,
      /**
       * To inject something with DI decorators in deps array, use
       * [new Decorator(), new Decorator(),..., TOKEN]
       * syntax.
       *
       * In this case you get 'null' if there are no value for
       * OPTIONAL_TOKEN
       */
      deps: [[new Optional(), OPTIONAL_TOKEN]],
      useFactory: someTokenFactory
    }
  ]
```

Thanks

**Comment by ChristianKohler** [comment]
Hey @phhien203 

Thank you for your input. There is more detail on that further down the infographic:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/4374178/162775328-ce66077e-42c9-48d7-91bf-dfefe29d2a9f.png">

Is that what you were looking for?
